general:
  output_path: "./output/output.json"
  log_path: "./logs/monitoring.json"
  interval: 20s 

# Memory Metrics Configuration
# 1. making the values true will add them to the memory metrics report.
memory:
  enabled: true
  total: true
  available: true
  used: true
  free: true
  used_percent: true
  active: false
  inactive: false
  buffers: false
  cached: true
  shared: false
  slab: false
  dirty: false

  swap_total: false
  swap_used: false
  swap_free: false
  swap_used_percent: false
  swap_in: false
  swap_out: false

cpu:
  enabled: true


# Disk Metrics Configuration
# 1. mounted: true means only mounted partitions will be monitored from selected paths.
# 2. putting '*' in paths_to_watch_disk will monitor all partitions.
# 3. sort_by parameters -> used_space, free_space, total_space, used_percent
disk:
  - enabled: true
    mounted: true
    paths_to_watch:
      - "/"
    filter:
      sort_by: used_percent
      top_disk_size: 3
      top_disk_usage: 2
      top_disk_usage_percent: 2
      top_free_space: 1

  # - enabled: true
  #   mounted: true
  #   paths_to_watch:
  #     - "/"
  #   filter:
  #     sort_by: free_space
  #     top_disk_size: 3
      

processes:
  - enabled: true
    filter:
      # running_hour_threshold: 0
      top_memory_usage: 3
      # top_cpu_usage: 0
      # state: ""
      # parent_pid: 0
      # tty: ""

  # - enabled: true
  #   filter:
  #     top_running_time: 3
  #     top_cpu_usage: 2
  #     tty: "?"
      
  - enabled: true
    filter:
      state: "S"
      top_cpu_usage: 4

permissions:
  - enabled: true
    paths:
      - "/home"
      - "/var/www/bookstore"
    show_user_permissions: true
    check_user_access:
      - "intern"

  - enabled: true
    paths:
      - "/home/furkan"
    show_user_permissions: false
    check_user_access:
      - "furkan"
      - "intern"
    
  - enabled: true
    paths:
      - "/opt/monitoring-merged/main.go"
    show_user_permissions: true
    check_user_access:
      - "furkan"
      - "root" 

network:
  enabled: true
  interfaces: true

  external_targets:
    - "https://www.google.com:443"
    - "34.42.118.72:80"
    - "10.10.0.4:22"
    - "34.171.30.76:3306"

  connections:
    - protocols: [tcp]
      ports: [80]
      state: [ESTABLISHED, TIME_WAIT, CLOSE_WAIT, LISTEN]
      program_name: [nginx]

    - ports: [3306]

    - pid: [95195, 126166]

alerter:
  enabled: true
  log_path: "./logs/alerter.json"
  alert_thresholds:
    memory:
        enabled: true
        usage_percent: 80
    disk:
      - enabled: true
        usage_percent: 80
        paths_to_watch:
          - "/"
    cpu:
      - enabled: true
        usage_percent: 80
