general:
  output_path: "./output/output.json"
  interval: 20s

memory:
  enabled: true
  total: true
  available: true
  used: true
  free: true
  used_percent: true
  active: false
  inactive: false
  buffers: false
  cached: true
  shared: false
  slab: false
  dirty: false

  swap_total: false
  swap_used: false
  swap_free: false
  swap_used_percent: false
  swap_in: false
  swap_out: false

cpu:
  enabled: true

# sort_by parameters -> used_space, free_space, total_space, used_percent
disk:
  - enabled: true
    mounted: true
    paths_to_watch:
      - "*"
    filter:
      sort_by: used_percent
      top_disk_size: 3
      top_disk_usage: 2
      top_disk_usage_percent: 2
      top_free_space: 1

  - enabled: true
    mounted: true
    paths_to_watch:
      - "/"
    filter:
      sort_by: free_space
      top_disk_size: 3
      

processes:
  - enabled: true
    filter:
      running_hour_threshold: 24
      top_memory_usage: 5
      top_cpu_usage: 4
      state: "Z"
      parent_pid: 1
      tty: "?"

  - enabled: true
    filter:
      top_running_time: 3
      top_cpu_usage: 2
      tty: "?"
      
  - enabled: true
    filter:
      state: "S"

permissions:
  enabled: true
  paths:
    - "/home"
    - "/etc"

# network:
#   enabled: true
#   check_open_ports: true
#   check_interfaces: true
