general:
  output_path: "./output/output.json"
  log_path: "./logs/monitoring.log"
  interval: 10 # in seconds

# Memory Metrics Configuration
# 1. making the values true will add them to the memory metrics report.
memory:
  enabled: true
  total: true
  available: true
  used: true
  free: true
  used_percent: true
  active: true
  inactive: false
  buffers: false
  cached: true
  shared: false
  slab: false
  dirty: false

  swap_total: false
  swap_used: false
  swap_free: false
  swap_used_percent: false
  swap_in: false
  swap_out: false

cpu:
  enabled: true


# Disk Metrics Configuration
# 1. mounted: true means only mounted partitions will be monitored from selected paths.
# 2. putting '*' in paths_to_watch_disk will monitor all partitions.
# 3. sort_by parameters -> used_space, free_space, total_space, used_percent
disk:
  - enabled: true
    mounted: true
    paths_to_watch:
      - "*"
    filter:
      sort_by: used_percent
      top_disk_size: 3
      top_disk_usage: 2
      top_disk_usage_percent: 2
      top_free_space: 1

  - enabled: true
    mounted: true
    paths_to_watch:
      - "/"
    filter:
      sort_by: free_space
      top_disk_size: 3
      

processes:
  - enabled: true
    filter:
      # running_hour_threshold: 0
      # top_memory_usage: 0
      # top_cpu_usage: 0
      # state: ""
      # parent_pid: 0
      # tty: ""
      limit_processes: 3

  # - enabled: true
  #   filter:
  #     top_running_time: 3
  #     top_cpu_usage: 2
  #     tty: "?"
      
  # - enabled: true
  #   filter:
  #     state: "S"

permissions:
  enabled: true
  paths:
    - "/home"
    - "/etc"

# network:
#   enabled: true
#   check_open_ports: true
#   check_interfaces: true

alerter:
  enabled: true
  alert_thresholds:
    memory:
      used_percent: 80
    disk:
      used_percent: 90
