# ==================================
# General Configuration
# ==================================
general:
  output_path: "/var/log/monitoring/metrics/output.json"
  # log_path: "/var/log/monitoring/logs/monitoring.json"
  log_path: "./logs/monitoring.json"
  interval: 60s
  remote:
    enabled: true
    host: "10.10.0.6"
    user: "ubuntu"
    remote_path: "/var/log/remote/test-server-output.json"
  web:
    enabled: true
    server: "10.10.0.7"
    user: "ubuntu"
    web_path: "/var/log/web/test-server-output.json"


# ==================================
# Memory Metrics Configuration
# ==================================
# Set each memory metric to true to include it in the report.
memory:
  enabled: true
  total: true
  available: true
  used: true
  free: true
  used_percent: true
  active: false
  inactive: false
  buffers: false
  cached: true
  shared: false
  slab: false
  dirty: false

  # Swap memory metrics
  swap_total: false         # Total swap space
  swap_used: false          # Swap space used
  swap_free: false          # Available swap space
  swap_used_percent: false  # Swap usage percentage
  swap_in: false            # Pages swapped in from disk
  swap_out: false           # Pages swapped out to disk

# ==================================
# CPU Metrics Configuration
# ==================================
# This enables CPU monitoring, which includes:
# - CPU info
# - Per-core usage
# - Total usage
# - Load averages
# - Time spent in system/use
cpu:
  enabled: true


# =========================
# Disk Metrics Configuration
# =========================
# mounted: true means only mounted partitions will be monitored from selected paths.
# paths_to_watch: List of paths or use '*' to include all
# 
# filter options:
#   sort_by: Sort disks by 'used_space', 'free_space', 'total_space', or 'used_percent'
#   top_disk_size: Show top N disks with the largest total space
#   top_disk_usage: Show top N disks with highest used space
#   top_disk_usage_percent: Show top N disks with highest used space in percent
#   top_free_space: Show top N disks with most available space
disk:
  - enabled: true
    mounted: true
    paths_to_watch:
      - "/"
    filter:
      sort_by: used_percent
      top_disk_size: 3
      top_disk_usage: 2
      top_disk_usage_percent: 2
      top_free_space: 1

  # - enabled: true
  #   mounted: true
  #   paths_to_watch:
  #     - "/"
  #   filter:
  #     sort_by: free_space
  #     top_disk_size: 3


# =========================
# Process Metrics Configuration
# =========================
# For each process group:
# - Results are filtered based on these fields.
#
# filter options:
#   running_hour_threshold: Only include processes running longer than this (in hours)
#   top_memory_usage: Show top N processes by memory usage
#   top_cpu_usage: Show top N processes by CPU usage
#   state: Filter processes by state ("R" = running, "S" = sleeping, "Z" = zombie, etc.)
#   parent_pid: Only include child processes of this parent PID
#   tty: Filter processes by controlling terminal ("?", "tty1", etc.)
processes:
  - enabled: true
    filter:
      # running_hour_threshold: 0
      top_memory_usage: 3
      # top_cpu_usage: 0
      # state: ""
      # parent_pid: 0
      # tty: ""

  # - enabled: true
  #   filter:
  #     top_running_time: 3
  #     top_cpu_usage: 2
  #     tty: "?"
      
  - enabled: true
    filter:
      state: "S"
      top_cpu_usage: 4


# ==================================
# Permissions Check Configuration
# ==================================
# Checks ownership and access permissions for given paths.
#
# fields:
#   paths: List of paths or files to check
#   show_owner_metadata: Whether to include UID/GID/username/group
#   check_user_access: List of usernames to check access for each path
permissions:
  - enabled: true
    paths:
      - "/home"
      - "/var/www/bookstore"
    show_owner_metadata: true
    check_user_access:
      - "intern"

  - enabled: true
    paths:
      - "/home/furkan"
    show_user_permissions: false
    check_user_access:
      - "furkan"
      - "intern"
    
  - enabled: true
    paths:
      - "/opt/monitoring-merged/main.go"
    show_user_permissions: true
    check_user_access:
      - "furkan"
      - "root" 

# ==================================
# Network Metrics Configuration
# ==================================
# Monitors both external network reachability and active connections.
#
# interfaces: true → List network interfaces and their IPs, MTU, flags, etc.
# external_targets: List of domains/IPs and ports to test via ICMP, TCP, DNS, HTTP
# connections: Active socket filters
#   protocols: e.g. [tcp, udp]
#   ports: e.g. [80, 443]
#   state: e.g. [ESTABLISHED, LISTEN]
#   program_name: Filter by owning process name for the connection
#   pid: Filter by owning process ID for the connection
network:
  enabled: true
  interfaces: true

  external_targets:
    - "https://www.google.com:443"
    - "34.42.118.72:80"
    - "10.10.0.4:22"
    - "34.171.30.76:3306"

  connections:
    - protocols: [tcp]
      ports: [80]
      state: [ESTABLISHED, TIME_WAIT, CLOSE_WAIT, LISTEN]
      program_name: [nginx]

    - ports: [3306]

    - pid: [95195, 126166]

services:
  enabled: true
  manager: "systemctl"   # "systemctl", "supervisorctl"
  filter:
    state: failed         # state: active, inactive, failed, activating, deactivating, reloading
    sub_state: running    # sub_state: running, exited, dead, auto-restart, reload, listening, etc.
    enable_state: static  # enable_state: enabled, disabled, static, masked, indirect, generated, transient

  service_list:
    # - "nginx"
    # - "mysql"
    # - "supervisor"
    # - "php-fpm"
    - "all"

# ==================================
# Alerting Configuration
# ==================================
# Writes alerts to the specified log file when thresholds are exceeded.
#
# Fields per resource:
#   enabled: true → Enable alerting for the resource
#   usage_percent: Trigger an alert if usage exceeds this %
alerter:
  enabled: true
  log_path: "/var/log/monitoring/logs/alerter.json"
  alert_settings:
    memory:
        enabled: true
        usage_percent: 80
    disk:
      - enabled: true
        usage_percent: 80
        paths_to_watch:
          - "/"
    cpu:
      enabled: true
      usage_percent: 80.0
